/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Dois ml (https://sketchfab.com/limamarcelo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pokedex-pixel-art-dd9e8c05b168495998d83a14a03cb1a1
Title: Pokedex Pixel art
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Pokedex({ opened, ...props }) {
  const { nodes, materials } = useGLTF("/models/pokedex.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.pokedex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.outline}
        />
        <group rotation={[opened ? Math.PI / 6 : Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials.pokedex}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.outline}
          />
          <group position={[0, 0.057, -0.004]} rotation={[Math.PI, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.pokedex}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_11.geometry}
              material={materials.outline}
            />
          </group>
        </group>
        <group position={[-0.053, -0.052, -0.003]} rotation={[0, 0, 0.002]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials["gastle-aura"]}
            position={[0, -0.008, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials.pokedex}
            position={[0, -0.008, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_18.geometry}
            material={materials.pokedex}
            position={[0, -0.008, 0]}
          />
        </group>
        <group position={[-0.032, -0.04, -0.003]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_23.geometry}
            material={materials.pokedex}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_24.geometry}
            material={materials.outline}
          />
        </group>
        <group position={[-0.015, -0.008, -0.007]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_26.geometry}
            material={materials.pokedex}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_27.geometry}
            material={materials.outline}
          />
        </group>
        <group position={[-0.054, -0.035, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_29.geometry}
            material={materials.pokedex}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_30.geometry}
            material={materials.outline}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.pokedex}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.outline}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_32.geometry}
          material={materials.pokedex}
          position={[-0.031, -0.014, -0.01]}
          rotation={[0, 0, -0.779]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/pokedex.glb");
